# Import parameters

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# load data sets

In [58]:

df=pd.read_csv(r"C:\projects\E-Commerce Behavior Data from Multi-Category Store\data\raw\2019-Oct.csv")
df2=pd.read_csv(r"C:\projects\E-Commerce Behavior Data from Multi-Category Store\data\raw\2019-Nov.csv")

KeyboardInterrupt:

# Inspect data set

## check if data sets are loaded correctly

### df1

In [ ]:
df.head()
#Data set loaded correctly.

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

### df2

In [ ]:
df2.head()
#Data set loaded correctly.

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

## check the shape of the data sets

### df1

In [ ]:
df.shape
# The first data set df has 42448764 entries and 9 columns.

(42448764, 9)

### df2

In [ ]:
df2.shape
# The second data set df2 has 67501979 entries and 9 columns

(67501979, 9)

## check the info of the data sets

### df1

In [ ]:
df.info()
# The first data set df has 42448764 entries and 9 columns confirming the shape of the data set.
# the column event_time is in object format, we need to convert it to datetime format.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42448764 entries, 0 to 42448763
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 2.8+ GB

### df2

In [ ]:
df2.info()
# The second data set df2 has 67501979 entries and 9 columns confirming the shape of the data set.
# the column event_time is in object format, we need to convert it to datetime format.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67501979 entries, 0 to 67501978
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 4.5+ GB

## check column names and that if both data sets have the same structure

### df1

In [ ]:
df.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

### df2

In [ ]:
df2.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

### both columns are ['event_time', 'event_type', 'product_id', 'category_id','category_code', 'brand', 'price', 'user_id', 'user_session'],dtype='object
### hence they both carry the same structure

## check for missing values

### df1

In [ ]:
df.isnull().sum()
# there are missing values in category_code (13515609 entries), brand (6117080 entries) and user_session (2 entries) columns

event_time              0
event_type              0
product_id              0
category_id             0
category_code    13515609
brand             6117080
price                   0
user_id                 0
user_session            2
dtype: int64

### df2

In [ ]:
df2.isnull().sum()
# there are missing values in category_code (21898171 entries), brand (9224078 entries) and user_session (10 entries) columns

event_time              0
event_type              0
product_id              0
category_id             0
category_code    21898171
brand             9224078
price                   0
user_id                 0
user_session           10
dtype: int64

## check for duplicates

### df1

In [ ]:
df.duplicated().sum() 
# there are np.int64(30220) duplicate entries in the first data set

np.int64(30220)

### df2

In [ ]:
df2.duplicated().sum()
# there are np.int64(100519) duplicate entries in the second data set

np.int64(100519)

## check statistical summary

### df1

In [ ]:
df.describe()
# df has price ranging from 0 to a max of 2574.07 with mean price of 290.32 ,there are no negative prices shown in the data set, the standard deviation is 358.27 which is higher than the mean price indicating that there are some outliers in the data set.

         product_id   category_id         price       user_id
count  4.244876e+07  4.244876e+07  4.244876e+07  4.244876e+07
mean   1.054993e+07  2.057404e+18  2.903237e+02  5.335371e+08
std    1.188191e+07  1.843926e+16  3.582692e+02  1.852374e+07
min    1.000978e+06  2.053014e+18  0.000000e+00  3.386938e+07
25%    1.005157e+06  2.053014e+18  6.598000e+01  5.159043e+08
50%    5.000470e+06  2.053014e+18  1.629300e+02  5.296965e+08
75%    1.600030e+07  2.053014e+18  3.585700e+02  5.515788e+08
max    6.050001e+07  2.175420e+18  2.574070e+03  5.662809e+08

### df2

In [ ]:
df2.describe()
# df2 has price ranging from 0 to 2574.07 with mean price of 292.45 ,there are no negative prices shown in the data set, the standard deviation is 355.67 which is higher than the mean price indicating that there are some outliers in the data set.

         product_id   category_id         price       user_id
count  6.750198e+07  6.750198e+07  6.750198e+07  6.750198e+07
mean   1.251406e+07  2.057898e+18  2.924593e+02  5.386397e+08
std    1.725741e+07  2.012549e+16  3.556745e+02  2.288516e+07
min    1.000365e+06  2.053014e+18  0.000000e+00  1.030022e+07
25%    1.305977e+06  2.053014e+18  6.924000e+01  5.164762e+08
50%    5.100568e+06  2.053014e+18  1.657700e+02  5.350573e+08
75%    1.730075e+07  2.053014e+18  3.603400e+02  5.610794e+08
max    1.000286e+08  2.187708e+18  2.574070e+03  5.799699e+08

# Event-type distribution

## event_type_counts_df1

In [ ]:
event_type_counts_df1 = df['event_type'].value_counts()
print(event_type_counts_df1)
#event_type_counts_df1 has the following counts: view(40779399),cart(926516)and purchase(742849)
#it shows that the majority of the events in the data set are views, followed by purchases and then carts, which is expected in an e-commerce setting where users typically view products more frequently than they add them to their carts or make purchases.

event_type
view        40779399
cart          926516
purchase      742849
Name: count, dtype: int64

## event_type_counts_df2

In [ ]:
event_type_counts_df2 = df2['event_type'].value_counts()
print(event_type_counts_df2)
#event_type_counts_df2 has the following counts: view(63556110),cart(3028930)and purchase(916939)
#it shows that the majority of the events in the data set are views, followed by purchases and then carts, which is expected in an e-commerce setting where users typically view products more frequently than they add them to their carts or make purchases.

event_type
view        63556110
cart         3028930
purchase      916939
Name: count, dtype: int64

# Event-type distribution comparison

## Merge datasets for combined analysis

In [ ]:
consolidated_df = pd.concat([df, df2], ignore_index=True)
print(consolidated_df.head())
#successfully merged the two data sets for combined analysis.

                event_time event_type  product_id          category_id  \
0  2019-10-01 00:00:00 UTC       view    44600062  2103807459595387724
1  2019-10-01 00:00:00 UTC       view     3900821  2053013552326770905
2  2019-10-01 00:00:01 UTC       view    17200506  2053013559792632471
3  2019-10-01 00:00:01 UTC       view     1307067  2053013558920217191
4  2019-10-01 00:00:04 UTC       view     1004237  2053013555631882655

                         category_code     brand    price    user_id  \
0                                  NaN  shiseido    35.79  541312140
1  appliances.environment.water_heater      aqua    33.20  554748717
2           furniture.living_room.sofa       NaN   543.10  519107250
3                   computers.notebook    lenovo   251.74  550050854
4               electronics.smartphone     apple  1081.98  535871217

                           user_session
0  72d76fde-8bb3-4e00-8c23-a032dfed738c
1  9333dfbd-b87a-4708-9857-6336556b0fcc
2  566511c2-e2e3-422b-b695-cf8e6e792ca8
3  7c90fc70-0e80-4590-96f3-13c02c18c713
4  c6bd7419-2748-4c56-95b4-8cec9ff8b80d

## Analyze event type distribution over time

In [ ]:
consolidated_df['month'] = pd.to_datetime(consolidated_df['event_time']).dt.month
event_type_counts_by_month = consolidated_df.groupby('month')['event_type'].value_counts().unstack().fillna(0)
print(event_type_counts_by_month)
#This indicates an increase in all event types from October to November.

event_type     cart  purchase      view
month
10           926516    742849  40779399
11          3028930    916939  63556110

## Calculate month-over-month changes

In [ ]:
event_type_counts_by_month.diff()
print(event_type_counts_by_month.diff())
# The month-over-month changes indicate a significant increase in 'view'by (22776711.0) and 'cart' by (2102414.0) events from October to November, while 'purchase' by (174090.0) events show a more modest increase.

event_type       cart  purchase        view
month
10                NaN       NaN         NaN
11          2102414.0  174090.0  22776711.0

# Zero-price investigation

## How many rows have price == 0

In [ ]:
zero_price_df = consolidated_df[consolidated_df['price'] == 0]
zero_price_df.count()
# There are 256761 rows with price == 0

event_time       256761
event_type       256761
product_id       256761
category_id      256761
category_code    123546
brand                 0
price            256761
user_id          256761
user_session     256761
month            256761
dtype: int64

## Which event types have price == 0?

In [ ]:
zero_price_df['event_type'].value_counts()
# Among the zero-price entries, there are 252203 'view' events, 4558 'cart' events, and 0 'purchase' events as they are also not displayed in the data set. This suggests that the zero-price entries are likely associated with product views and cart additions, but not with actual purchases, which could indicate that these entries may represent products that were viewed or added to carts but not purchased, possibly due to being out of stock, promotional items, or data entry errors and possibly due to customer changing their minds about purchasing the product after viewing or adding it to the cart. Further investigation would be needed to determine the exact reason for the zero-price entries.

event_type
view    252203
cart      4558
Name: count, dtype: int64

## Which categories have been affected or infer the view and cart with no purchase?

In [ ]:
zero_price_df['category_code'].value_counts()

category_code
apparel.shoes                 18894
electronics.smartphone        11310
electronics.video.tv           7975
furniture.living_room.sofa     7930
computers.notebook             7607
                              ...
country_yard.lawn_mower           4
sport.tennis                      4
appliances.kitchen.fryer          3
apparel.shorts                    2
apparel.shoes.espadrilles         1
Name: count, Length: 123, dtype: int64

# Session sanity sample

## Pick one user_session

In [ ]:
sample_user_session = consolidated_df['user_session'].iloc[0]
sample_user_session_df = consolidated_df[consolidated_df['user_session'] == sample_user_session]
print(sample_user_session_df)

                 event_time event_type  product_id          category_id  \
0   2019-10-01 00:00:00 UTC       view    44600062  2103807459595387724
13  2019-10-01 00:00:15 UTC       view    44600062  2103807459595387724

   category_code     brand  price    user_id  \
0            NaN  shiseido  35.79  541312140
13           NaN  shiseido  35.79  541312140

                            user_session  month
0   72d76fde-8bb3-4e00-8c23-a032dfed738c     10
13  72d76fde-8bb3-4e00-8c23-a032dfed738c     10

## Sort by event_time

In [ ]:
sample_user_session_df = sample_user_session_df.sort_values(by='event_time')
print(sample_user_session_df)

                 event_time event_type  product_id          category_id  \
0   2019-10-01 00:00:00 UTC       view    44600062  2103807459595387724
13  2019-10-01 00:00:15 UTC       view    44600062  2103807459595387724

   category_code     brand  price    user_id  \
0            NaN  shiseido  35.79  541312140
13           NaN  shiseido  35.79  541312140

                            user_session  month
0   72d76fde-8bb3-4e00-8c23-a032dfed738c     10
13  72d76fde-8bb3-4e00-8c23-a032dfed738c     10

In [ ]:
#Manually inspect the event order
#The sample user session shows a logical sequence of events: multiple 'view' events however no 'cart' or 'purchase' events.

# Session duration analysis

## user session calculations:

### user_session_times

In [ ]:
session_times = consolidated_df.groupby('user_session')['event_time'].agg(['min', 'max'])

### start_time

In [ ]:
start_time = session_times['min']
print(start_time.head())

user_session
00000042-3e3f-42f9-810d-f3d264139c50    2019-10-18 10:54:45 UTC
00000056-a206-40dd-b174-a072550fa38c    2019-10-31 06:23:12 UTC
0000007c-adbf-4ed7-af17-d1fef9763d67    2019-11-18 09:16:19 UTC
00000083-8816-4d58-a9b8-f52f54186edc    2019-10-06 11:24:45 UTC
0000009d-1f5b-40b9-bd23-db4f3d973ae3    2019-11-13 06:02:54 UTC
Name: min, dtype: object

### End_time

In [ ]:
end_time = session_times['max']
print(end_time.head())

user_session
00000042-3e3f-42f9-810d-f3d264139c50    2019-10-18 10:55:20 UTC
00000056-a206-40dd-b174-a072550fa38c    2019-10-31 06:31:25 UTC
0000007c-adbf-4ed7-af17-d1fef9763d67    2019-11-18 09:16:19 UTC
00000083-8816-4d58-a9b8-f52f54186edc    2019-10-06 11:34:30 UTC
0000009d-1f5b-40b9-bd23-db4f3d973ae3    2019-11-13 06:02:54 UTC
Name: max, dtype: object

### duration (in minutes)

In [ ]:
duration = (pd.to_datetime(end_time) - pd.to_datetime(start_time)).dt.total_seconds() / 60
print(duration.head())

user_session
00000042-3e3f-42f9-810d-f3d264139c50    0.583333
00000056-a206-40dd-b174-a072550fa38c    8.216667
0000007c-adbf-4ed7-af17-d1fef9763d67    0.000000
00000083-8816-4d58-a9b8-f52f54186edc    9.750000
0000009d-1f5b-40b9-bd23-db4f3d973ae3    0.000000
dtype: float64

### Identify extreme cases (very short, very long)

In [ ]:
duration.describe() 
# The session durations range from 0.0 minutes to 87481.22 minutes with a mean duration of 18.34 minutes.

count    2.301665e+07
mean     1.833978e+01
std      4.776998e+02
min      0.000000e+00
25%      0.000000e+00
50%      1.016667e+00
75%      4.633333e+00
max      8.748122e+04
dtype: float64

### session_times

In [ ]:
session_times

,min,max
user_session,,
00000042-3e3f-42f9-810d-f3d264139c50,2019-10-18 10:54:45 UTC,2019-10-18 10:55:20 UTC
00000056-a206-40dd-b174-a072550fa38c,2019-10-31 06:23:12 UTC,2019-10-31 06:31:25 UTC
0000007c-adbf-4ed7-af17-d1fef9763d67,2019-11-18 09:16:19 UTC,2019-11-18 09:16:19 UTC
00000083-8816-4d58-a9b8-f52f54186edc,2019-10-06 11:24:45 UTC,2019-10-06 11:34:30 UTC
0000009d-1f5b-40b9-bd23-db4f3d973ae3,2019-11-13 06:02:54 UTC,2019-11-13 06:02:54 UTC
...,...,...
fffffbbc-3c59-46fb-9165-fa46f027e332,2019-11-11 08:33:43 UTC,2019-11-11 08:33:43 UTC
fffffbbe-9f76-403b-b17c-e7c68c48ea1c,2019-11-17 09:43:04 UTC,2019-11-17 09:48:15 UTC
fffffc65-7ce9-435c-8b72-1d9f7062fe77,2019-10-11 06:10:23 UTC,2019-10-11 06:10:54 UTC
fffffd01-5f95-4916-b2dd-491c603d6c9c,2019-11-17 14:07:11 UTC,2019-11-17 14:12:46 UTC
fffffde2-4522-4b44-8a32-510c55739ba1,2019-11-30 10:29:57 UTC,2019-11-30 10:29:57 UTC

## Event Counts per Session

In [ ]:
event_counts_per_session = consolidated_df.groupby('user_session')['event_type'].value_counts().unstack().fillna(0)

## Total number of events per session

In [ ]:
event_counts_per_session['total_events']=event_counts_per_session.sum(axis=1)
print

## Number of views (event_type == 'view')

In [ ]:
event_counts_per_session['view']

user_session
00000042-3e3f-42f9-810d-f3d264139c50     2.0
00000056-a206-40dd-b174-a072550fa38c     8.0
0000007c-adbf-4ed7-af17-d1fef9763d67     1.0
00000083-8816-4d58-a9b8-f52f54186edc    16.0
0000009d-1f5b-40b9-bd23-db4f3d973ae3     1.0
                                        ...
fffffbbc-3c59-46fb-9165-fa46f027e332     1.0
fffffbbe-9f76-403b-b17c-e7c68c48ea1c     4.0
fffffc65-7ce9-435c-8b72-1d9f7062fe77     2.0
fffffd01-5f95-4916-b2dd-491c603d6c9c     3.0
fffffde2-4522-4b44-8a32-510c55739ba1     1.0
Name: view, Length: 23016650, dtype: float64

## Number of carts (event_type == 'cart')

In [ ]:
event_counts_per_session['cart']

user_session
00000042-3e3f-42f9-810d-f3d264139c50    0.0
00000056-a206-40dd-b174-a072550fa38c    0.0
0000007c-adbf-4ed7-af17-d1fef9763d67    0.0
00000083-8816-4d58-a9b8-f52f54186edc    1.0
0000009d-1f5b-40b9-bd23-db4f3d973ae3    0.0
                                       ...
fffffbbc-3c59-46fb-9165-fa46f027e332    0.0
fffffbbe-9f76-403b-b17c-e7c68c48ea1c    0.0
fffffc65-7ce9-435c-8b72-1d9f7062fe77    0.0
fffffd01-5f95-4916-b2dd-491c603d6c9c    2.0
fffffde2-4522-4b44-8a32-510c55739ba1    0.0
Name: cart, Length: 23016650, dtype: float64

## Number of purchases (event_type == 'purchase')

In [ ]:
event_counts_per_session['purchase']

user_session
00000042-3e3f-42f9-810d-f3d264139c50    0.0
00000056-a206-40dd-b174-a072550fa38c    0.0
0000007c-adbf-4ed7-af17-d1fef9763d67    0.0
00000083-8816-4d58-a9b8-f52f54186edc    1.0
0000009d-1f5b-40b9-bd23-db4f3d973ae3    0.0
                                       ...
fffffbbc-3c59-46fb-9165-fa46f027e332    0.0
fffffbbe-9f76-403b-b17c-e7c68c48ea1c    0.0
fffffc65-7ce9-435c-8b72-1d9f7062fe77    0.0
fffffd01-5f95-4916-b2dd-491c603d6c9c    1.0
fffffde2-4522-4b44-8a32-510c55739ba1    0.0
Name: purchase, Length: 23016650, dtype: float64

# 1-dentify unusual sessions:

## Sessions with purchases but zero views

In [ ]:
event_counts_per_session[(event_counts_per_session['purchase'] > 0) & (event_counts_per_session['view'] == 0)]

event_type                            cart  purchase  view  total_events
user_session
000e06d7-aef0-4093-8ee6-2f3966b71345   0.0       1.0   0.0           1.0
0015ddfa-870e-4ae2-9979-528b20b0451a   1.0       1.0   0.0           2.0
001cc3e1-43c8-42b5-9595-34ea4ac533ec   0.0       1.0   0.0           1.0
001d78a3-2f8d-43ee-bb0d-e8fd37b5446e   1.0       1.0   0.0           2.0
001d8ddd-de63-4e8e-9ea9-6c78d43c2a67   1.0       1.0   0.0           2.0
...                                    ...       ...   ...           ...
ffe37849-f755-4de9-a1d7-ec352407bd41   1.0       1.0   0.0           2.0
ffe56e28-b9ca-405e-a8fb-4ab6ea794873   0.0       1.0   0.0           1.0
fff032ac-3589-484b-9ab6-afff7a3061f0   1.0       1.0   0.0           2.0
fffbf89b-316f-498c-b45b-1490e242c55d   0.0       1.0   0.0           1.0
fffd1dba-a2e5-48c9-a450-85df00a97112   2.0       1.0   0.0           3.0

[6786 rows x 4 columns]

## Sessions with dozens of purchases

In [ ]:
event_counts_per_session[event_counts_per_session['purchase'] >= 2]

event_type                            cart  purchase  view  total_events
user_session
00004ada-8f93-49a6-956d-4ed71ae94791   0.0       2.0   4.0           6.0
00005b76-13ba-4afe-b80d-2f2b337d3e92   0.0       2.0   8.0          10.0
00007b3f-ec7a-4d2e-ac44-64dfec829806   0.0       2.0   3.0           5.0
0000c091-07d6-42b6-a7d8-75732b489429   5.0       2.0   5.0          12.0
0000de39-dc74-414d-8da6-83ad56135bf5   4.0       4.0  12.0          20.0
...                                    ...       ...   ...           ...
fffcc946-4682-4328-8d68-92d155112fd7   3.0       2.0  25.0          30.0
ffff15c0-016a-4ad9-8a32-982fab93ae39   2.0       2.0   3.0           7.0
ffffc739-b299-4029-ab70-84d81cb32e0d   3.0       2.0   7.0          12.0
fffff038-a8d6-4c8a-9bf3-afe71b52733a   2.0       2.0   6.0          10.0
fffff736-405e-485f-ac84-6a622ef44329   2.0       2.0  16.0          20.0

[180465 rows x 4 columns]

## Sessions with very high total events

In [ ]:
event_counts_per_session[event_counts_per_session['total_events'].describe()['75%'] < event_counts_per_session['total_events']]

event_type                            cart  purchase  view  total_events
user_session
00000056-a206-40dd-b174-a072550fa38c   0.0       0.0   8.0           8.0
00000083-8816-4d58-a9b8-f52f54186edc   1.0       1.0  16.0          18.0
000001fd-1f89-45e8-a3ce-fe3218cabfad   4.0       1.0   6.0          11.0
00000616-f016-4c01-b323-438486d9d3ee   0.0       0.0   8.0           8.0
000009c4-a1dd-4764-87d9-24f3d7e43c4f   0.0       0.0   9.0           9.0
...                                    ...       ...   ...           ...
fffff736-405e-485f-ac84-6a622ef44329   2.0       2.0  16.0          20.0
fffff7e1-9294-4d6c-8482-e1438ba88380   0.0       0.0   6.0           6.0
fffff8d4-d31c-4066-a00b-2ace84d33640   0.0       0.0  12.0          12.0
fffff956-3426-4d37-9de9-4c00ec4ddeac   0.0       0.0  48.0          48.0
fffffd01-5f95-4916-b2dd-491c603d6c9c   2.0       1.0   3.0           6.0

[5571139 rows x 4 columns]

# 2-Summarize distributions:

## Minimum, maximum, mean, median per event type per session

### Min

In [ ]:
event_counts_per_session.min()
#event type per session minimums are: cart(0.0), purchase(0.0), total_events(1.0), view(0.0)

event_type
cart            0.0
purchase        0.0
view            0.0
total_events    1.0
dtype: float64

### Max

In [ ]:
event_counts_per_session.max()
#event type per session maximums are: cart(709.0), purchase(100.0), total_events(4128.0), view(4128.0)

event_type
cart             709.0
purchase         100.0
view            4128.0
total_events    4128.0
dtype: float64

### Mean

In [ ]:
event_counts_per_session.mean()
#event type per session means are: cart(0.17), purchase(0.07), total_events(4.78), view(4.53)

event_type
cart            0.171851
purchase        0.072112
view            4.533045
total_events    4.777008
dtype: float64

### Median

In [ ]:
event_counts_per_session.median()
#event type per session medians are: cart(0.0), purchase(0.0), total_events(2.0), view(2.0)

event_type
cart            0.0
purchase        0.0
view            2.0
total_events    2.0
dtype: float64

## event type per session percentiles

In [ ]:
event_counts_per_session.describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])  
#event type per session percentiles are:cart: 25%(0.0), 50%(0.0), 75%(0.0), 90%(1.0), 95%(1.0), 99%(3.0) purchase: 25%(0.0), 50%(0.0), 75%(0.0), 90%(0.0), 95%(1.0), 99%(1.0) total_events: 25%(1.0), 50%(2.0), 75%(5.0), 90%(11.0), 95%(17.0), 99%(35.0) view: 25%(1.0), 50%(2.0), 75%(5.0), 90%(10.0), 95%(16.0), 99%(34.0)

event_type          cart      purchase          view  total_events
count       2.301665e+07  2.301665e+07  2.301665e+07  2.301665e+07
mean        1.718510e-01  7.211249e-02  4.533045e+00  4.777008e+00
std         8.130932e-01  3.217360e-01  7.266151e+00  7.453235e+00
min         0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
25%         0.000000e+00  0.000000e+00  1.000000e+00  1.000000e+00
50%         0.000000e+00  0.000000e+00  2.000000e+00  2.000000e+00
75%         0.000000e+00  0.000000e+00  5.000000e+00  5.000000e+00
90%         1.000000e+00  0.000000e+00  1.000000e+01  1.100000e+01
95%         1.000000e+00  1.000000e+00  1.600000e+01  1.700000e+01
99%         3.000000e+00  1.000000e+00  3.400000e+01  3.500000e+01
max         7.090000e+02  1.000000e+02  4.128000e+03  4.128000e+03

# 🧱 Step 1 — Proper Data Type Correction

In [ ]:
consolidated_df['event_time'] = pd.to_datetime(
    consolidated_df['event_time'],
    utc=True,
    errors='coerce'
)

In [ ]:
consolidated_df['event_time'].isna().sum()

np.int64(0)

# 🧹 Step 2 — Clean Critical Fields

## 1. Remove exact duplicates

In [ ]:
consolidated_df = consolidated_df.drop_duplicates()

## 2. Handle missing sessions

In [ ]:
consolidated_df = consolidated_df.dropna(subset=['user_session'])

# 🧠 Step 3 — Feature Engineering

## A) Revenue Column

In [ ]:
consolidated_df['revenue'] = np.where(
    consolidated_df['event_type'] == 'purchase',
    consolidated_df['price'],
    0
)

## B) Date Features

In [ ]:
consolidated_df['date'] = consolidated_df['event_time'].dt.date
consolidated_df['hour'] = consolidated_df['event_time'].dt.hour
consolidated_df['day_of_week'] = consolidated_df['event_time'].dt.weekday

# 🏗 Step 4 — Create Curated Analytical Tables

## 1️⃣ Session-Level Fact Table

In [ ]:
session_fact = consolidated_df.groupby('user_session').agg(
    user_id=('user_id', 'first'),
    category_id=('category_id', 'first'),
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max'),
    total_events=('event_type', 'count'),
    total_views=('event_type', lambda x: (x == 'view').sum()),
    total_carts=('event_type', lambda x: (x == 'cart').sum()),
    total_purchases=('event_type', lambda x: (x == 'purchase').sum()),
    revenue=('revenue', 'sum')
).reset_index()

session_fact['session_duration_minutes'] = (
    (session_fact['session_end'] - session_fact['session_start'])
    .dt.total_seconds() / 60
)

## 2️⃣ Product-Level Fact Table

In [ ]:
product_fact = (
    consolidated_df
    .groupby(['date', 'product_id'])
    .agg(
        category_id=('category_id', 'first'),
        brand=('brand', 'first'),
        avg_price=('price', 'mean'),
        total_views=('event_type', lambda x: x.eq('view').sum()),
        total_carts=('event_type', lambda x: x.eq('cart').sum()),
        total_purchases=('event_type', lambda x: x.eq('purchase').sum()),
        revenue=('revenue', 'sum')
    )
    .reset_index()
)

## 3️⃣ Daily Metrics Table

In [ ]:
daily_metrics = consolidated_df.groupby('date').agg(
    total_events=('event_type', 'count'),
    total_views=('event_type', lambda x: (x == 'view').sum()),
    total_carts=('event_type', lambda x: (x == 'cart').sum()),
    total_purchases=('event_type', lambda x: (x == 'purchase').sum()),
    revenue=('revenue', 'sum')
).reset_index()

# 🧪 Step 5 — Strategic Quality Check
Check session duration sanity

In [ ]:
session_fact['session_duration_minutes'].describe(percentiles=[0.95,0.99])

count    2.301665e+07
mean     1.833978e+01
std      4.776998e+02
min      0.000000e+00
50%      1.016667e+00
95%      2.286667e+01
99%      8.125000e+01
max      8.748122e+04
Name: session_duration_minutes, dtype: float64

# 💾 Step 6 — Export Curated Layer

In [ ]:
session_fact.to_csv("session_fact.csv", index=False)
product_fact.to_csv("product_fact.csv", index=False)
daily_metrics.to_csv("daily_metrics.csv", index=False)

# Upload ssession_fact to sql directly as is big file

In [ ]:
# Convert to datetime, remove timezone
session_fact['session_start'] = pd.to_datetime(session_fact['session_start'], errors='coerce').dt.tz_localize(None)
session_fact['session_end'] = pd.to_datetime(session_fact['session_end'], errors='coerce').dt.tz_localize(None)

# Drop rows that failed conversion
session_fact = session_fact.dropna(subset=['session_start', 'session_end'])

# Format as SQL-friendly string
session_fact['session_start'] = session_fact['session_start'].dt.strftime('%Y-%m-%d %H:%M:%S')
session_fact['session_end'] = session_fact['session_end'].dt.strftime('%Y-%m-%d %H:%M:%S')

# Save CSV
csv_path = r"C:\projects\E-Commerce Behavior Data from Multi-Category Store\python\session_fact_clean.csv"
session_fact.to_csv(csv_path, index=False, encoding='utf-8')

In [ ]:
import csv

session_fact.to_csv(
    csv_path,
    index=False,
    encoding='utf-8',
    quoting=csv.QUOTE_NONE,  # same as 3
    escapechar='\\'           # escape commas and special chars
)

In [ ]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};SERVER=MBETHIE-PC\SQLEXPRESS;DATABASE=E-commerce_project;Trusted_Connection=yes;"
)
cursor = conn.cursor()
cursor.fast_executemany = True

insert_sql = """
INSERT INTO session_fact
(user_session, user_id, category_id, session_start, session_end, total_events, total_views, total_carts, total_purchases, revenue, session_duration_minutes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"""

for row in session_fact.itertuples(index=False):
    cursor.execute(insert_sql, row)

conn.commit()
cursor.close()
conn.close()